### ISSUE TITLE
FloatingLabel doesn't have name in the props 

### ISSUE THREAD

**Issue by ICTServ** [shinokada/svelte-5-ui-lib#2]
### Describe the bug

Object literal may only specify known properties, and '"name"' does not exist in type '{ children: (this: void) => unique symbol & { _: "functions passed to {@render ...} tags must use the `Snippet` type imported from \"svelte\""; }; id?: string | undefined; style?: "filled" | ... 2 more ... | undefined; ... 6 more ...; labelclass?: string | undefined; }'.ts(2353)
(property) "name": string

### Reproduction

				<FloatingLabel size="small" style="filled" id="full_name" name="full_name" type="text" inputclass="rounded-md">
					Full name
				</FloatingLabel>

### Version and System Info

```shell
svelte-5-ui-lib v0.3.7
```

**Comment by shinokada** [comment]
If you find the library useful, please consider to support it.
https://ko-fi.com/codewithshin

**Comment by shinokada** [comment]
Fixed for the latest vesion.
