### ISSUE TITLE
Passing an `<input>` tag inside the children/default snippet on the `<Input>` component does not replace the input 

### ISSUE THREAD

**Issue by mtablang** [shinokada/svelte-5-ui-lib#20]
### Describe the bug

I was expecting it work to like its svelte 4 version:
https://flowbite-svelte.com/docs/forms/input-field#Advanced_usage

For my specific use case, I needed this behavior to be able to manually set the `.focus()` on the input (since that method is not existing in the main `Input` component). I wonder if there are other workarounds for this?

### Reproduction

```ts
<script lang="ts">
	function setFocus() {
	  nativeInput.focus();  // Focus on the native input element
	}
</script>

<Input>
	<input bind:this={nativeInput} />
</Input>
  
```

### Version and System Info

```shell
svelte-5-ui-lib 0.9.9
```

**Comment by shinokada** [comment]
I'm not sure this PR solve your problem. But the Input component passes props back up to the consumer.
Please see an example, Advanced usage at https://svelte-5-ui-lib.codewithshin.com/forms/input-field.
This will be included in the next release.

**Comment by mtablang** [comment]
Hi, thanks so much for this! I tested the latest release (0.9.15) and it solved my issue.
