### ISSUE TITLE
Installation instructions not correct

### ISSUE THREAD

**Issue by Hugos68** [shinokada/svelte-5-ui-lib#22]
### Describe the bug

In the installation instructions it states to set `runes` to `true` in compileroptions but this is not needed and actually probably bad advice as it will force all your deps to be svelte 5 syntax otherwise it won't compile. If svelte sees you're using runes it will dynamically compile with or without runes, so ideally this step in the installation instructions is removed.

### Reproduction

not relevant

### Version and System Info

```shell
not relevant
```

**Comment by shinokada** [comment]
Thanks. It used to be required to run Runes. I will check it and update the doc.

**Comment by shinokada** [comment]
Since it is in the [Svelte 5 preview doc](https://svelte-5-preview.vercel.app/docs/runes#how-to-opt-in), I will rephrase it.
