### ISSUE TITLE
Please add Tabs and Carousel 

### ISSUE THREAD

**Issue by ICTServ** [shinokada/svelte-5-ui-lib#3]
I hope this message finds you well. I recently had the opportunity to use svelte-5-ui-lib, and I was immensely impressed by the quality and utility of the project. I wanted to extend my deepest gratitude for your dedication and hard work in creating and maintaining such a valuable resource.  Thanks for Your Incredible Open-Source Contribution!

**Comment by shinokada** [comment]
If you find the library useful, please consider to support it.
https://ko-fi.com/codewithshin

**Comment by ICTServ** [comment]
> If you find the library useful, please consider to support it. https://ko-fi.com/codewithshin

sure I will starting from the end of this month

**Comment by shinokada** [comment]
Tabs components are added.
https://svelte-5-ui-lib.codewithshin.com/components/tab
For carousel, I'd suggest to use specialized component for flexibility. See this discussion, https://www.reddit.com/r/sveltejs/comments/zyj7ry/where_to_find_a_good_carousel_for_sveltekit/
