### ISSUE TITLE
Missing close/open button Sidebar

### ISSUE THREAD

**Issue by PasVegan** [shinokada/svelte-5-ui-lib#31]
### Describe the bug

Neither the close or open button are showing in the Sidebar component.

### Reproduction

Got to the [demo](https://svelte-5-ui-lib.codewithshin.com/components/sidebar) and select the Close button example.
![image](https://github.com/user-attachments/assets/becb044d-df7b-45c6-95db-2f82ee4a8237)

### Version and System Info

```shell
Browser: brave, firefox
```

**Comment by shinokada** [comment]
You need to resize the browser.

![image](https://github.com/user-attachments/assets/539f52f7-4ac8-47a1-976a-7d36212541ee)
