### ISSUE TITLE
Typo in button component - tailwind css 

### ISSUE THREAD

**Issue by fouf96** [shinokada/svelte-5-ui-lib#32]
See:

https://github.com/shinokada/svelte-5-ui-lib/blob/6b0a02d6461b7d7e53e967095e8fc51f87c8a5d9/src/lib/buttons/theme.ts#L75

an s is missing at the beginning. should be `class: "shadow-gray-500/50 dark:shadow-gray-800/80"`

**Comment by shinokada** [comment]
Fixed. Thank you.
