### ISSUE TITLE
FIX: '"onclick"' does not exist in type

### ISSUE THREAD

**Issue by ICTServ** [shinokada/svelte-5-ui-lib#4]
Please add `onclick?: () => void;` to the following declaration in the components that use onclick event such as Button, Avatar, Dropdown, ... etc.  
`declare const __propDef: {
    props: {
        onclick?: () => void;
    };
}`

**Comment by shinokada** [comment]
Since all components have `...attributes` props, you can add any events in [Svelte: Runes](https://svelte-5-preview.vercel.app/docs/old-vs-new#forwarding-events).

I know it gives type warnings, but I hope Svelte language support adjust it in future.

What do you think?

**Comment by ICTServ** [comment]
I think better to add onclick defenition as optional parameter in the propDef, since no need to pass its value it automatically recognise onclick event and stop warning. onclick is heavily used event, instead of having warning it is better to eliminate the warning. I test it and it fix the issue. I don't see any downside of adding to declare const __propDef whether they fix it in the  future or not. I happy to contribute if want to.

**Comment by shinokada** [comment]
I can add to some components, but not that simple since there are quite few A11y restrictions. I will add to some components but I will leave the rest to users.

**Comment by shinokada** [comment]
v0.4.5 is published.
