### ISSUE TITLE
Allow to pass some generic value to modal.open() function

### ISSUE THREAD

**Issue by superrnovae** [shinokada/svelte-5-ui-lib#43]
### Describe the bug

I have a list of items, and each item has a delete button.
When the delete button is clicked I'd like to pass some value to the open() function, but currently it is not supported.
Would it be possible to implement such functionality so that the value is accessable by children?

### Reproduction

-

### Version and System Info

```shell
-
```

**Comment by superrnovae** [comment]
nevermind, I thought there was some additional logic to the open function, but it seems like it just sets the visibility flag.

**Comment by shinokada** [comment]
This makes me think adding a callback function to `uiHelper` can be a good idea.
